name: GHA Workflow

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: compile
        run: echo "compile started..."

      - name: produce-binary
        run: sleep 10

      - name: push-binary
        run: echo "binary pushing..."

      - name: register-build-artifacts
        uses: cloudbees-gha-cbp/register-build-artifact@main
        id: go-action
        with:
          name: "gha-artifact-test-1"
          version: 1.0.0
          url: "docker.io/calculi-corp/gha-action/gha-artifact-2:latest"
          digest: "sha256:d4a123ee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2"
          type: "docker"
          cloudbees-url: "https://api.saas-preprod.beescloud.com"
          cloudbees-pat: ${{ secrets.CBP_PAT }}

  test:
    runs-on: ubuntu-latest
    needs: [build]   # Depends on 'build' job
    steps:
      - name: Run tests
        run: echo "tests running..."

      - name: Collect test results
        run: sleep 17

      - name: Publish test results
        run: echo "Sending Test Results to CBP"


  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]   # Depends on both 'build' and 'test' jobs
    steps:
      - name: prepare-deployment
        run: sleep 15
      - name: deploy app
        run: echo "Invoking CBP Deploy Workflow..."


